[tool.poetry]
name = "openlabeling"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "~3.8.10"
lxml = "~4.3.0"
numpy = "~1.16.0"
opencv-contrib-python = "~3.4.9.33"
tqdm = "~4.29.1"
PySimpleGUI = "^4.55.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
